### ISSUE TITLE
Project compiles in Visual Studio but not in Xamarin Studio

### ISSUE THREAD

**Issue by wenyonk** [ellisnet/Portable.Data.Sqlite#3]
ISSUE NOT ENHANCEMENT
Issue was reported by a customer who was using the nuget package
Portable.Data.Sqlite. However I was able to recreate this issue using the
samples provided on github in the Portable.Data.Sqlite repository. The issue is
that though the iOS sample and the referenced Portable.Data.Sqlite library
compile and run fine in Visual Studio, the same fails in Xamarin Studio. I
checked with both Mono 3.16.0.68 and Mono 3.12.0.76.

ALSO SEE:
https://bugzilla.xamarin.com/show_bug.cgi?id=26753
https://bugzilla.xamarin.com/show_bug.cgi?id=26960

**Comment by ellisnet** [comment]
Will test compiling the new [SimpleAdo.Sqlite](https://github.com/ellisnet/SimpleAdo) library with Visual Studio for the Mac; to see if the new library also has this problem.

**Comment by ellisnet** [comment]
I don't have any problems compiling the new library - [SimpleAdo.Sqlite](https://github.com/ellisnet/SimpleAdo), including SimpleAdo.Core and SimpleAdo.Sqlite - using Visual Studio for Mac version 7.2.2 (build 11).  However, the unit tests library does not compile.  I believe this is to be expected, since Visual Studio for Mac does not yet support compiling .NET (classic) libraries (to my knowledge).
